### ISSUE TITLE
labels for jenks breaks overlap with some narrow maps

### ISSUE THREAD

**Issue by jspeis** [d3plus/d3plus-geomap#13]
The legend labels for some maps using jenks breaks overlap with each other which can make the legend hard to read.

### Expected Behavior
To have labels avoid overlapping. Either,
1. increased vertical spacing if insufficient horizontal space available or
2. perhaps if too narrow, some labels could only appear on hover? 

just some ideas

### Current Behavior

![screen shot 2017-10-10 at 3 56 04 pm](https://user-images.githubusercontent.com/87581/31407640-8d9572f0-add3-11e7-8f46-9aabd30153cd.png)
 
### Steps to Reproduce (for bugs)

1. https://jsfiddle.net/neuyy41a/

### Your Environment
OSX / Chrome

**Comment by davelandry** [comment]
Fixed in d3plus-axis https://github.com/d3plus/d3plus-axis/releases/tag/v0.3.37
