### ISSUE TITLE
attribution for OpenStreetMap

### ISSUE THREAD

**Issue by cserpell** [d3plus/d3plus-geomap#35]
Hi all,

I noticed that in many pages using this library, default CARTO tiles are used, which are based on OpenStreetMap data, without giving proper attribution. Is it possible to have an easy way to add attribution within this library?

Thanks,

**Comment by davelandry** [comment]
absolutely! we'll have to add something in. @cserpell can you post a link here to CARTO/OSM's terms of use?

**Comment by cserpell** [comment]
Sure, https://www.openstreetmap.org/copyright/

**Comment by frabarz** [comment]
In Leaflet the attribution looks like this: 
> © <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, © <a href="https://carto.com/attribution">CARTO</a>

**Comment by davelandry** [comment]
released with version 0.6.13. can be overridden by setting the `attribution` method

**Comment by cserpell** [comment]
Thank you!
